### ISSUE TITLE
Video rotation information ignored

### ISSUE THREAD

**Issue by whlsxl** [pulsejet/go-vod#15]
Play video shoot by iPhone, the rotation information ignored.
Play without go-vod.

<img width="1723" alt="Screenshot 2023-06-11 at 02 51 23" src="https://github.com/pulsejet/go-vod/assets/305995/7b6729fa-7713-44ca-94ae-bfa5806d6270">

Play with go-vod.

<img width="1728" alt="Screenshot 2023-06-11 at 02 52 15" src="https://github.com/pulsejet/go-vod/assets/305995/1947699d-5545-427c-9209-db039b83d42f">

```
    Metadata:
    Side data:
      displaymatrix: rotation of -90.00 degrees
```

**Comment by pulsejet** [comment]
1. What version of memories?
2. What version of go-vod?
3. Using external transcoder?
4. Using hw acceleration?
