### ISSUE TITLE
AMDGPU fails with `-low_power 1`

### ISSUE THREAD

**Issue by prurigro** [pulsejet/go-vod#18]
When running with vaapi in an amdgpu (at least rdna2), if the `-low_power 1` flag is set then transcoding fails with `No usable encoding entrypoint found for profile VAProfileH264Main`. Removing that flag gets it working. This wasn't happening to me on my previous server with an intel GPU.

It might be good to document this somewhere (documenting how the config file works could be useful too!)

Thanks for building this useful tool :)

**Comment by pulsejet** [comment]
There's no config file. You should be configuring this from the Memories admin dashboard.

**Comment by prurigro** [comment]
Ahh interesting- my external go-vod instance wasn't running with hardware acceleration despite being toggled on in the memories admin dashboard (with intel and amd) so I assumed that only applied to the local instance. My solution was to just patch the sources so hardware acceleration was forced on. Similarly I patched the sources to remove the low_power flag to get things working on amd.

I have no experience with nvidia either, but amd supports vaapi and in theory works exactly the same as intel provided the right system packages are installed, but I guess support for the `low_power` flag is one difference.

**Comment by pulsejet** [comment]
Stale
