### ISSUE TITLE
Best way to run go-vod on persistent server

### ISSUE THREAD

**Issue by Kybeer** [pulsejet/go-vod#20]
What's the best way to have go-vod running all the time on a physical server?

shell script that starts this with cron on boot?
```
CGO_ENABLED=0 go build -ldflags="-s -w"
./go-vod
```

I intend to use it for Memories transcoding. Nextcloud with Memories is running containerized on a VM.

**Comment by Kybeer** [comment]
Or perhaps it's always best to build a container for go-vod?

Do I need to explicitly present ffmpeg binary to Memories, or is it enough to use external go-vod for both video thumbnail view, and transcode?

Sorry for multiple questions in the same issue

**Comment by pulsejet** [comment]
https://memories.gallery/hw-transcoding/

**Comment by Kybeer** [comment]
> 1. You do need ffmpeg in the Nextcloud container for preview generation. But note that an older ffmpeg version is fine here, since it won't be used for transcoding.
> 
>     2. Currently the only way to run go-vod separately is to have the same mounts on both Nextcloud and the go-vod containers. This is done easiest with docker-compose, as the Memories  docs describe. But if you can achieve a similar effect with something else then it'll be equivalent.

Thanks for the quick reply. Any tips of getting ffmpeg presented to the Nextcloud container? I cannot think of any.. I'm using the official one and prefer to do so.

**Comment by pulsejet** [comment]
Honestly I'm completely clueless why the images don't bundle ffmpeg among other things. There's an "official" docker recipe for building an image that has all the dependencies (again, no idea why this isn't standard)
https://github.com/nextcloud/docker/blob/master/.examples/dockerfiles/full/fpm/Dockerfile

**Comment by Kybeer** [comment]
> Honestly I'm completely clueless why the images don't bundle ffmpeg among other things. There's an "official" docker recipe for building an image that has all the dependencies (again, no idea why this isn't standard) https://github.com/nextcloud/docker/blob/master/.examples/dockerfiles/full/fpm/Dockerfile

Yes my thought as well.

We can go ahead and close this issue. Thanks for the insights.
