### ISSUE TITLE
Which version of go-vod to clone??

### ISSUE THREAD

**Issue by WGandy** [pulsejet/go-vod#26]
```
myhost: git clone -b 5.5.3 https://github.com/pulsejet/go-vod
Cloning into 'go-vod'...
fatal: Remote branch 5.5.3 not found in upstream origin
```

The instructions say to put the version of memories in as a -b tag but the tags for go-vod don't appear to correspond.  Furthermore, I understand that the -b option is to specify a branch, not a tag?? 

What am I missing?

**Comment by pulsejet** [comment]
Use `0.1.16` for now.

Basically the docs are too new. On master: 
![image](https://github.com/pulsejet/go-vod/assets/10709794/b9f13028-4361-498a-af81-69498c8b72a3)
