### ISSUE TITLE
Add NVIDIA dependencies to build script

### ISSUE THREAD

**Issue by pulsejet** [pulsejet/go-vod#8]
We use `build-ffmpeg.sh` to build the docker image to run an external go-vod service. This already contains the drivers for Intel QSV, but NVENC is missing.

**Comment by pulsejet** [comment]
Any idea if this is possible @MB-Finski ?

**Comment by Markvis** [comment]
Hi, i opened a PR to add a separate Dockerfile and build-script for nvidia gpu users
https://github.com/pulsejet/go-vod/pull/12
