### ISSUE TITLE
Not seeing much in the docs - NVENC

### ISSUE THREAD

**Issue by travisboss** [pulsejet/go-vod#9]
How does one use an nvidia card with go-vod?  I have a P2000 working fine in jellyfin(using nvidia-docker) but want to use this so I can use that card in Nextcloud.

Thanks.

**Comment by pulsejet** [comment]
https://github.com/pulsejet/memories/wiki/HW-Transcoding

**Comment by pulsejet** [comment]
Please open issues at memories except for bugs in go-vod
